---
- name: "Provision Image"
  hosts: all
  become: yes

  tasks:
    - name: Install NGinx
      package:
        name: nginx
        state: present

    - name: Create index.html
      ansible.builtin.copy:
        # src: index.html
        dest: /usr/share/nginx/html/index.html
        # content: Hello, World
        content: |
          <html>
            <head><title>Hello, World</title></head>
            <body>
              <h1>Hello, World!</h2>
            </body>
          </html>

    - name: Enable NGinx
      service:
        name: nginx
        enabled: yes

    - name: Start NGinx
      service:
        name: nginx
        state: started
